import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import { MemoryRouter } from 'react-router-dom';
import TwoStepInquiryForm from './TwoStepInquiryForm';
const { rpc } = vi.hoisted(() => ({ rpc: vi.fn() }));
vi.mock('@/integrations/supabase/client', () => ({ supabase: { rpc } }));
beforeEach(() => rpc.mockReset());
it('waits for saving, retains step on failure, and retries completion using the same token', async () => {
  rpc.mockResolvedValueOnce({ error: { message: 'offline' } }).mockResolvedValueOnce({ error: null }).mockResolvedValueOnce({ error: { message: 'offline' } }).mockResolvedValueOnce({ error: null });
  render(<MemoryRouter><TwoStepInquiryForm /></MemoryRouter>);
  fireEvent.change(screen.getByLabelText('Full Name'), { target: { value: 'Jane' } });
  fireEvent.change(screen.getByLabelText('Phone Number'), { target: { value: '5085550123' } });
  fireEvent.click(screen.getByRole('button', { name: /Continue/ }));
  await screen.findByRole('alert');
  expect(screen.queryByLabelText('Email Address')).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: /Continue/ }));
  await screen.findByLabelText('Email Address');
  expect(screen.getByLabelText('Email Address')).toHaveFocus();
  expect(rpc.mock.calls[0][1].p_token).toBe(rpc.mock.calls[1][1].p_token);
  fireEvent.change(screen.getByLabelText('Email Address'), { target: { value: 'jane@example.com' } });
  fireEvent.change(screen.getByLabelText('ZIP Code'), { target: { value: '02108' } });
  fireEvent.change(screen.getByLabelText('Street Address'), { target: { value: '123 Test Street' } });
  fireEvent.click(screen.getByRole('button', { name: /Complete My/ }));
  await screen.findByRole('alert');
  expect(screen.getByLabelText('Street Address')).toHaveValue('123 Test Street');
  fireEvent.click(screen.getByRole('button', { name: /Complete My/ }));
  await waitFor(() => expect(rpc).toHaveBeenCalledTimes(4));
  expect(rpc.mock.calls[3][1]).toEqual({ p_token: rpc.mock.calls[0][1].p_token, p_name: 'Jane', p_phone: '5085550123', p_details: { email: 'jane@example.com', zip: '02108', address: '123 Test Street' } });
});
